name: Daily CVE Release List

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate_cve_list:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      # Generate the CVE list and commit changes
      - name: Generate and commit CVE list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_FULL_NAME: <owner>/<repository>
          BRANCH_NAME: <branch_name>
          DIRECTORY: cve_data
        run: |
          python generate_cve_list.py --directory $DIRECTORY
          python commit_cve_files_to_repo.py --github-token $GITHUB_TOKEN \
                                             --repo-full-name $REPO_FULL_NAME \
                                             --branch-name $BRANCH_NAME \
                                             --file-names $(ls -1 $DIRECTORY/*.zip)
